#!/usr/bin/env php
<?php
use \Rych\ByteSize\ByteSize;

require __DIR__ . '/app/vendor/autoload.php';

$version = '6.0.0-BETA-1';

$unlim = new Symfony\Component\Finder\Finder();
$unlim->files()
    ->ignoreVCS(true)
    ->name('*')
    ->notPath('app/open')
    ->notPath('upload')
    ->notName('.gitignore')
    ->notName('composer.lock')
    ->notName('chmod')
    ->notName('build')
    ->notName('*.zip')
    ->notName('*.map')
    ->exclude('phpunit')
    ->exclude('Tests')
    ->exclude('test')
    ->exclude('tests')
    ->exclude('bin')
    ->in(__DIR__);

$zipName = "ElfChat-Unlim-$version.zip";
$zipFile = __DIR__ . '/' . $zipName;
createZip($unlim, $zipFile, $zipName, $version);

$pro = clone $unlim;
$pro->notName('server.php')
    ->notName('WebSocketServer.php')
    ->notName('WebSocketServerProxy.php')
    ->notPath('WebSocketServer');

$zipName = "ElfChat-Pro-$version.zip";
$zipFile = __DIR__ . '/' . $zipName;
createZip($pro, $zipFile, $zipName, $version);

function createZip($finder, $zipFile, $zipName, $version, $showAdded = false)
{
    if (file_exists($zipFile)) {
        unlink($zipFile);
    }

    $zip = new ZipArchive();
    if ($zip->open($zipFile, ZipArchive::CREATE) !== true) {
        die("Can not open zip archive\n");
    }

    $count = 0;
    /** @var $file \Symfony\Component\Finder\SplFileInfo */
    foreach ($finder as $file) {

        if ($showAdded) {
            $name = $file->getRelativePathname();
            if (strlen($name) >= 70) {
                $name = substr($name, 0, 33) . '...' . substr($name, -33);
            }
            echo "Add file: $name \n";
        }
        $count++;

        $zip->addFile($file->getRealPath(), $file->getRelativePathname());
    }

    $zip->addFile(__DIR__ . '/.htaccess', '.htaccess');
    $zip->addFile(__DIR__ . '/app/.htaccess', 'app/.htaccess');

    $zip->addEmptyDir('app/open');
    $zip->addEmptyDir('upload');

    $zip->setArchiveComment("(c) ElfChat $version by Elfet\nSite: http://elfchat.net");

    $zip->close();

    echo "=====================================================\n";
    echo "Zip archive created: $zipName\n";
    echo "Total files: " . $count . "\n";
    echo "Total size: " . ByteSize::formatMetric(filesize($zipFile)) . "\n";
}