#!/usr/bin/env php
<?php
use \Rych\ByteSize\ByteSize;

require __DIR__ . '/app/vendor/autoload.php';

$version = '6.0.0 BETA 1';

$finder = new Symfony\Component\Finder\Finder();
$finder->files()
    ->ignoreVCS(true)
    ->name('*')
    ->notPath('app/open')
    ->notPath('upload')
    ->notName('.gitignore')
    ->notName('composer.lock')
    ->notName('bootstrap.php')
    ->notName('chmod')
    ->notName('build')
    ->notName('*.zip')
    ->notName('*.map')
    ->notName('LICENSE_*.htm')
    ->exclude('phpunit')
    ->exclude('Tests')
    ->exclude('test')
    ->exclude('tests')
    ->exclude('bin')
    ->in(__DIR__);

/**
 * UNLIM edition build
 */

$unlim = clone $finder;

$edition = "UNLIM";
$zipName = "ElfChat $version $edition.zip";
$zipFile = __DIR__ . '/' . $zipName;
createZip($unlim, $zipFile, $zipName, $version, $edition);


/**
 * PRO edition build
 */

$pro = clone $finder;
$pro->notName('server.php')
    ->notName('WebSocketServer.php')
    ->notName('WebSocketServerProxy.php')
    ->notPath('WebSocketServer');

$edition = "PRO";
$zipName = "ElfChat $version $edition.zip";
$zipFile = __DIR__ . '/' . $zipName;
createZip($pro, $zipFile, $zipName, $version, $edition);


/**
 * Build function
 */

function createZip($finder, $zipFile, $zipName, $version, $edition, $showAdded = false)
{
    echo "Start creating zip archive...\n";

    if (file_exists($zipFile)) {
        unlink($zipFile);
    }

    $zip = new ZipArchive();
    if ($zip->open($zipFile, ZipArchive::CREATE) !== true) {
        die("Can not open zip archive\n");
    }

    $count = 0;
    /** @var $file \Symfony\Component\Finder\SplFileInfo */
    foreach ($finder as $file) {

        if ($showAdded) {
            $name = $file->getRelativePathname();
            if (strlen($name) >= 70) {
                $name = substr($name, 0, 33) . '...' . substr($name, -33);
            }
            echo "Add file: $name \n";
        }
        $count++;

        $zip->addFile($file->getRealPath(), $file->getRelativePathname());
    }


    $content = file_get_contents(__DIR__ . '/app/bootstrap.php');
    $content = str_replace('__VERSION__', $version, $content);
    $content = str_replace('__EDITION__', $edition, $content);
    $zip->addFromString('app/bootstrap.php', $content);

    $zip->addFile(__DIR__ . '/.htaccess', '.htaccess');
    $zip->addFile(__DIR__ . '/app/.htaccess', 'app/.htaccess');

    $zip->addEmptyDir('app/open');
    $zip->addEmptyDir('upload');

    if($edition === 'UNLIM') {
        $zip->addFile(__DIR__ . '/license/LICENSE_COMMERCIAL_USE.htm', 'LICENSE.htm');
    } else {
        $zip->addFile(__DIR__ . '/license/LICENSE_NO_COMMERCIAL_USE.htm', 'LICENSE.htm');
    }

    $zip->setArchiveComment("(c) ElfChat $version $edition by Elfet");

    $zip->close();

    echo "Zip archive created: $zipName\n";
    echo "Total files: " . $count . "\n";
    echo "Total size: " . ByteSize::formatMetric(filesize($zipFile)) . "\n";
}