#!/bin/bash

# Vendors build
# howler.min.js must be at the end.

cat \
lib/traceur-runtime.js \
lib/vendor/mustache/mustache.js \
lib/vendor/jquery.scrollto/index.js \
lib/vendor/jquery.hotkeys/jquery.hotkeys.js \
lib/vendor/moment/moment.js \
lib/insert-at-caret/insert.js \
lib/snap.js/snap.min.js \
lib/vendor/howler/howler.min.js \
> lib/vendors.js

# Minify vendors does not working now.
# java -jar lib/yuicompressor-2.4.8.jar --type js --nomunge --disable-optimizations -o lib/vendors.js lib/vendors.js

/usr/local/bin/traceur --sourcemap --out app.js \
--script src/Flyspeck.js \
--script src/Helpers.js \
--script src/Server/AbstractServer.js \
--script src/Server/WebSocketServer.js \
--script src/Server/AjaxServer.js \
--script src/Notify.js \
--script src/Sound.js \
--script src/Scroll.js \
--script src/Popover.js \
--script src/Views.js \
--script src/Users.js \
--script src/Emotion.js \
--script src/Filters.js \
--script src/Application.js \
--script src/Config.js