#!/bin/bash

# Vendors build
# howler.min.js must be at the end.

cat \
lib/traceur-runtime.js \
lib/vendor/mustache/mustache.js \
lib/vendor/jquery.scrollto/index.js \
lib/vendor/jquery.hotkeys/jquery.hotkeys.js \
lib/vendor/moment/moment.js \
lib/vendor/insert/insert.js \
lib/vendor/howler/howler.min.js \
> lib/vendors.js

# Minify vendors does not working now.
# java -jar lib/yuicompressor-2.4.8.jar --type js --nomunge --disable-optimizations -o lib/vendors.js lib/vendors.js

/usr/local/bin/traceur --sourcemap --out app.js \
--script src/config.js \
--script src/helpers.js \
--script src/server/AbstractServer.js \
--script src/server/WebSocketServer.js \
--script src/notify.js \
--script src/sound.js \
--script src/scroll.js \
--script src/Views.js \
--script src/server.js \
--script src/Users.js \
--script src/emotion.js \
--script src/filters.js \
--script src/popover.js \
--script src/Application.js